# Generated by Django 5.0.4 on 2024-07-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotereference',
            name='credit_note',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='returndate',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='VAT',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='advance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.purchasebill'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='tot_bill_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stockIn',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stockOut',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='hsn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='item',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='grandtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='salesinvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.invoice'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditnotehistory',
            name='credit_note_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.creditnote'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.creditnote'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='adjustment',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='grandtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='returnno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='subtotal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='taxamount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='debitnotehistory',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=10),
        ),
        migrations.AlterField(
            model_name='itemtransactions',
            name='trans_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions_party',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party'),
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, null=True)),
                ('hsn', models.CharField(blank=True, max_length=100)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('VAT', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(default=0, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('debitnote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.debitnote')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
